Develop
Damjan-Bulatovic-EY/mission-to-mars pull request #1
Opened 2021-06-28 12:30 UTC by Damjan-Bulatovic-EY

2021-06-28 13:22 UTC, Milica-Roljic-EY commented
Damjan, please make additional changes described below to improve styling and best code practices.

Component folders should be capitalized too, not only components.
Please update name to Carousel component instead of Card, to be semantically correct. 
You can create Card component as child component where you'll pass props from parent component Carousel. Card component should return jsx containing img, h3 as card title, and p to display card description (explanation).
Carousel should be centered.
Carousel cards have different image sizes, which makes carousel description text to overlap, update styling to have uniform styling.
Footer should be sticky.
![Screenshot 2021-06-28 145707](https://user-images.githubusercontent.com/85943191/123643347-90852800-d824-11eb-9911-c1b8f48bd165.png)
![Screenshot 2021-06-28 144651](https://user-images.githubusercontent.com/85943191/123643370-95e27280-d824-11eb-8732-f75be1cf1e34.png)

UseFetch hook should be placed in separate folder and that folder could be moved to separate folder, e.g. for utils, service, helpers, or simply hooks, since it is not actually a component.
Please move key for NASA API to separate file, since it is not a good practice to have it hardcoded in the code.
Some alt attributes are added, which is great, but not in all places, fix where is missing.
Fix console warning Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Card (http://localhost:3000/static/js/main.chunk.js:688:64)
    at div
    at Home
Missing bullets (dots) - let's try to add it after updating the PR with above mentioned changes. 
The Router can go to the separate file. (optional)

2021-06-28 13:34 UTC, Milica-Roljic-EY requested changes
Damjan, please make changes added in comment in Conversation tab.

2021-07-05 14:07 UTC, mitrovic-jovana commented on src/components/Card/Card.js
> +        <h3>{singleData.title}</h3>
This is a good place to use destructuring of singleData object

2021-07-05 14:07 UTC, mitrovic-jovana commented on src/components/Carusel/Carusel.js
> +  const key = process.env.REACT_APP_API_KEY;
Good job of using .env file for api keys

2021-07-05 14:28 UTC, mitrovic-jovana commented on src/components/Carusel/Carusel.js
> +import React, { useState, useEffect } from "react";
This component should be named **Carousel**, you have a typo

2021-07-05 14:33 UTC, mitrovic-jovana approved these changes
Good job Damjan, you definitely followed provided suggestions. 
I am merging this PR, however, try to spend some time fixing the design and UX a little bit. For example:
1.	Navigation arrows could be restyled, they are really small and hard to notice. Don’t put them directly next to the window edges
2.	Description in the carousel is still overflowing. Remove fixed height and add some padding
3.	You can add some spinner while you are waiting for the service response
4.	Since you don’t have pagination, one suggestion for better UX is to disable left arrow when you are at the beginning of the carousel and right arrow when you get to the end of carousel.
5.	Static pages (Terms and Conditions and Privacy Notice) could have some margin
6.	Work on adding pagination

One more thing you can improve, don’t invoke NASA’s service directly inside Carousel component. If you do that, Carousel is not customizable, and it can only work with response from that api. Invoke service in parent component and pass data to Carousel as props

2021-07-05 14:34 UTC, merged